<?xml version="1.0" encoding="UTF-8"?>
<!--
  Merge one or more SVRL documents into a single svrl:schematron-output.

  Input document: <merge><svrl href="relative-or-absolute-uri"/>...</merge>
  Each referenced document may be a plain SVRL file or any XML that contains
  svrl:schematron-output elements (e.g. the KoSIT validator's serialized
  createReportInput). All children of every schematron-output found are
  copied, in order, into one merged schematron-output.

  Optional severity overrides (the KoSIT scenario customLevel mechanism):
    $overrides-uri : URI of an overrides.xml generated by extract-overrides.xsl
    $scenario      : name of the scenario whose overrides apply
  A failed-assert or successful-report whose @id matches an override gets its
  @flag replaced by the override's flag. No other rewriting happens.
-->
<xsl:stylesheet version="3.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:svrl="http://purl.oclc.org/dsdl/svrl"
                exclude-result-prefixes="xs">

  <xsl:param name="overrides-uri" as="xs:string" select="''"/>
  <xsl:param name="scenario" as="xs:string" select="''"/>

  <xsl:output method="xml" indent="yes"/>

  <xsl:variable name="ov"
                select="if ($overrides-uri ne '')
                        then doc($overrides-uri)/overrides/scenario[@name eq $scenario]/rule
                        else ()"/>

  <xsl:template match="/">
    <svrl:schematron-output>
      <xsl:for-each select="/merge/svrl">
        <xsl:apply-templates select="doc(@href)//svrl:schematron-output/node()"/>
      </xsl:for-each>
    </svrl:schematron-output>
  </xsl:template>

  <xsl:template match="svrl:failed-assert | svrl:successful-report">
    <xsl:copy>
      <xsl:copy-of select="@*"/>
      <xsl:variable name="hit" select="$ov[@id eq current()/@id]"/>
      <xsl:if test="exists($hit)">
        <xsl:attribute name="flag" select="$hit[1]/@flag"/>
      </xsl:if>
      <xsl:apply-templates/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="element()">
    <xsl:copy>
      <xsl:copy-of select="@*"/>
      <xsl:apply-templates/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="text() | comment() | processing-instruction()">
    <xsl:copy/>
  </xsl:template>

</xsl:stylesheet>
